### ISSUE TITLE
Res Flag "Shoot"

### ISSUE THREAD

**Issue by Acheron4171** [mb243/THBL#10]
I think the flag "shoot" should be taken away from players. Someone could lure someone to their place, start spawning in mobs and the other person might be at an extreme disadvantage because their bow won't work.

**Comment by Acheron4171** [comment]
Also, "animal" is misspelled in the leash flag.

**Comment by mb243** [comment]
> Also, "animal" is misspelled in the leash flag.

Can you move this into a separate issue please?

**Comment by mb243** [comment]
> I think the flag "shoot" should be taken away from players.

Agreed. Working on this.

**Comment by Acheron4171** [comment]
Thank you.

**Comment by mb243** [comment]
No prob. Removed from config and from any existing land claims.
