### ISSUE TITLE
End Portal Stronghold Missing

### ISSUE THREAD

**Issue by Joiful88** [mb243/THBL#14]
When using Eye Of Ender to locate strongholds, the eye of ender eventually goes down, but no stronghold is located nearby.

**Comment by mb243** [comment]
Probably related to #4

**Comment by mb243** [comment]
Can you give coordinates for the location where the eye went down?

**Comment by Joiful88** [comment]
The item disappears at 183/31/-1752. It also seems to be glitching my character after throwing the item. I have trouble moving and I get the message "It looks like you might be glitching, please tap sneak"

**Comment by mb243** [comment]
Closing this for now as a duplicate while I continue to work on #4 

> It also seems to be glitching my character after throwing the item. I have trouble moving and I get the message "It looks like you might be glitching, please tap sneak"

If you're still seeing this, please open it as a new issue.
