### ISSUE TITLE
/tpa

### ISSUE THREAD

**Issue by Acheron4171** [mb243/THBL#15]
My /tpa requests have no timer on them. The request is sent out instantly. Is this bug or intentional?

**Comment by mb243** [comment]
¯\_(ツ)_/¯

**Comment by mb243** [comment]
Might be fixed now. Try again?

**Comment by mb243** [comment]
/tpa should have a warmup. If you're not seeing it, I'm curious to know if it's just you or other folks as well.

**Comment by mb243** [comment]
Confirmed on a test account.

**Comment by mb243** [comment]
Fixed
