### ISSUE TITLE
Teleporting quickly will trigger anti-cheat

### ISSUE THREAD

**Issue by RoBlockHead** [mb243/THBL#16]
I was trying to find my mine by using /random to go to the region. I was kicked for moving unexpectedly. I believe that the anti-cheat thinks that I'm speed-hacking.

**Comment by mb243** [comment]
I have a change to the anti-cheat coming at the next server reboot. Let me know if it fixes this.

**Comment by mb243** [comment]
Is this still happening?

**Comment by RoBlockHead** [comment]
Idk if it's happening. I'm currently at school.

**Comment by mb243** [comment]
Closing this one for now. If you're able to reproduce it, please leave a comment.

**Comment by mb243** [comment]
This is actually a confirmed upstream issue with the anti-cheat plugin. Tagged upstream, waiting for a fix in the plugin.
