### ISSUE TITLE
Dynmap

### ISSUE THREAD

**Issue by Acheron4171** [mb243/THBL#17]
I had an issue with Dynmap where it would force reloading of the page long before the map finished loading. It would do it so fast and often the the server would kick me for overloading it with requests.

**Comment by mb243** [comment]
What browser are you using? Does this occur on other browsers?

**Comment by Acheron4171** [comment]
I don't remember what browser/computer I was on and it hasn't happened again, to me, after that day. I just think that we should keep overviewer for a little bit longer.

**Comment by mb243** [comment]
I threw this in Discord to see if anyone else was having the same issue, and haven't seen any responses as of yet. Without anyone currently seeing the issue, I believe this is already resolved.

Taking a look at the website data, Dynmap is preferred more than 2:1 over Overviewer, and they both store LOTS of data on the disk. It's kinda pointless to run both (though they do show different things), and locking on one would free up disk space and reduce confusion.

**Comment by Acheron4171** [comment]
Can we see region post names and catacombs in Dynmap?

**Comment by mb243** [comment]
> Can we see region post names and catacombs in Dynmap?

This is not currently possible.

**Comment by Acheron4171** [comment]
Then under no circumstances are you to remove Overviewer. lol

**Comment by mb243** [comment]
> Then under no circumstances are you to remove Overviewer. lol

😏
