### ISSUE TITLE
Can we get the autosorter pluggin back?

### ISSUE THREAD

**Issue by RetroRadical** [mb243/THBL#18]
Ive gotten to the level of laziness that all i want for christmas is the auto sorter pluggin for inventory and chests

**Comment by mb243** [comment]
Calling this one what it is :)

**Comment by mb243** [comment]
Implemented the latest version of this plugin I could find. This will take effect tomorrow after the reboot.

Closing this one for now. If there are any issues with the new plugin, please open them as new issues.
