### ISSUE TITLE
Res is now leasing to the creator of a /res claim instead of indefinite ownership

### ISSUE THREAD

**Issue by RetroRadical** [mb243/THBL#19]
New player lhungry is making a res where it says that there is a life to his claim area. Through his interaction with /res create "Promise_Land", he seems to be stuck with paying a lease or loosing his stuff. I gave him 10000 to make sure he had enough money for the claim and saw him redo it. Idk what to do next.

**Comment by mb243** [comment]
Yea, this one was my fault.

Disabled the lease system, converted all 'leased' land claims to permanent and paid you back the $10k.

**Comment by RetroRadical** [comment]
Lol, you didnt have to give me the money back. Im kinda sitting pretty.

**Comment by mb243** [comment]
I know. But it was my fault, so... you're welcome :)
