### ISSUE TITLE
Climbing a ladder through a wooden trapdoor can trigger false-positive for flying

### ISSUE THREAD

**Issue by mb243** [mb243/THBL#2]
Working with Acheron on this one

**Comment by mb243** [comment]
Asked Ash to flip the trapdoor around and put up one more ladder block. Ash, please update and let me know if the issue still persists. If not, please close this issue.

**Comment by mb243** [comment]
Also pulled down a new version of the anti-cheat, but there aren't any notes to suggest changes that might impact this.

**Comment by mb243** [comment]
Ash - Any updates here?

**Comment by Acheron4171** [comment]
Flipped trapdoor around. Cannot place ladder where trapdoor was. Can get on top of the top ladder and jump out of the hole. Cannot just climb all the way out though.

**Comment by Acheron4171** [comment]
Issue also present with iron trapdoors.

**Comment by mb243** [comment]
Can you try building the ladder to the top of the column and the placing the trapdoor on top to see if this helps?

Let me know if you need a better explanation.

**Comment by mb243** [comment]
I have a change to the anti-cheat coming at the next server reboot. Let me know if it fixes this.

**Comment by mb243** [comment]
Is this still happening?

**Comment by Acheron4171** [comment]
I haven't had a chance to test it yet. We delivered 2 more litters of puppies yesterday.

**Comment by Acheron4171** [comment]
Issue persists.

**Comment by mb243** [comment]
Workaround:

Building a ladder to the top of the climb and placing the trapdoor at the top of the ladder works. For iron trapdoor control, you can place another block to the side of the trapdoor. 

I can see why this trips up the anti-cheat as the ladder ends one block before you're at ground level and technically you're flying to get up, but vanilla game mechanics seem to ignore this. Tricky to say how this would best be addressed.

**Comment by mb243** [comment]
Looks like this has already been reported to the anti-cheat plugin author. Going to close this for now while I watch for newer versions of the plugin. If anything else seems off, please open a new issue.
