### ISSUE TITLE
Fireworks and Leveling up in Mcmmo

### ISSUE THREAD

**Issue by RetroRadical** [mb243/THBL#21]
The definition of extra is when you get a firework explosion when you gain a level in mcmmo. Can this be removed?

**Comment by mb243** [comment]
> The definition of extra is when you get a firework explosion when you gain a level in mcmmo.

Sorry, I'm not quite sure exactly what you mean here. Is there a problem with the fireworks, or you're just not a fan of them entirely?

**Comment by RetroRadical** [comment]
They are slightly annoying. Can we toggle them off or remove them?

**Comment by mb243** [comment]
I think they're a nice touch, but I can set it to "every x number of levels" instead. 
How about every 10 levels?

**Comment by RetroRadical** [comment]
I can deal with that!!

**Comment by mb243** [comment]
Changed to every 10. Will take effect after the overnight update.
