### ISSUE TITLE
New player tutorial area

### ISSUE THREAD

**Issue by mb243** [mb243/THBL#22]
I'm interested in hearing thoughts on a new player tutorial area centered on 0/0. Conceptually, this would be a place where all new players would spawn that would have signs with commands, common-language words ("yes", "no", "ok", etc), and arrows indicating directions to move to learn more. Some examples of signs:

- "PvP OK"
- "/shop + /bal"
- "/tpa + /tpahere"
- "/help"

And signs that explain the region system and point to the region post

```
/help sethome
/help visit
bit.ly/mcregions
---->
```

etc.

As players move through the tutorial area, they will eventually emerge next to a region post and potentially a random teleporter. This would allow them to start exploring once they've acclimated, and give them a chance to get a grasp of the game mechanics without getting killed straight away (maybe).

Thoughts on this?

**Comment by Acheron4171** [comment]
Sounds like a worthwhile endeavor and I would be willing to but some time and effort into it at a later date. Most of my time is being taken by puppies and school.

**Comment by mb243** [comment]
Retro has been using the claim entry/exit messages in his own claim to add some flavor text. This might be a nice touch to the tutorial area, especially since the entry messages show more text than a sign.

**Comment by mb243** [comment]
Could also use a volunteer or two to help design/build this area. Ideally it should start as at/near 0/0 and then move towards one of the nearby region posts.

**Comment by mb243** [comment]
Closing this one for now due to lack of time/resources to make this happen. Might consider it again in the future.

**Comment by RetroRadical** [comment]
In my professional opinion, the rate we pick up new players is somewhat lacking. I don't know if it's intentional, desired, or the goal for new players coming in to be miniscule. If we spend all the time trying to make this elaborate Welcome Center but no one is on to use it, I feel like my effort is going to waste. I propose three things, one is to definitely reopen the motion to make a starting course, 2 is to come up with a system of advertising on forums to promote the server, and 3 is to redo City to accommodate for all of this. Our city area is really small and aesthetically unappealing in certain parts.

**Comment by mb243** [comment]
> I don't know if it's intentional, desired, or the goal for new players coming in to be miniscule. 

It's not any of these. I've noticed that players tend to participate more during downtimes in the year (school breaks, college breaks, etc), which makes sense. This doesn't seem to be a very popular time, but that doesn't mean that we can't get new players, it just makes it more of a challenge. 

> I propose three things, one is to definitely reopen the motion to make a starting course

Done.

> 2 is to come up with a system of advertising on forums to promote the server

This is already in place via servers lists which support a voting system, here:

https://thehardblocklife.com/vote/

Each of these voting entries is a listing for this server on each of these server lists. They support voting to help popular servers rise to the top, and I have a system in place to reward folks who vote. I don't push it or advertise it in-game because I don't feel that's an effective or favorable message, and the point is to allow folks who look for it to find it, not to force it upon folks to vote, or reward it in such a way as to cause an imbalance. I'm open to other suggestions here, but this part is already in place.

> 3 is to redo City to accommodate for all of this.

I'm down for this. The following changes would help make this happen:

- Renaming the closest region post to 'City', making the visit command `/visit city` instead of just `/city` (This is a necessary first step)
- Changing the `/city` command to show help text telling players to use `/visit city` instead
- Having a path built from that post to the actual City area.
- Claiming the area around X0/Z0 as a server claim and extending it to the nearest region post(s).
- Allowing players to build in the Tutorial area and giving it a rough, functional design to begin with. This would probably be best limited to players who are part of the moderator team.

Let me know your thoughts on this.

**Comment by RetroRadical** [comment]
Seems like a good start to making it. Instead of City what else could we name it, to better reflect the functionality of the location. I feel that letting just new players built here would not be beneficial unless they are given permission to do so. Like making it a server claim was exactly what I was thinking. Everyone is equal to build here that deserves to. I wouldn't want to come here and see some new person try to improve my design, doing a crappy job, and not even finishing it. I believe that to be a flaw with people building in The Old City. there are spots where people have started building but have claimed that no one can edit, and if this is supposed to be a group effort, I see this to be counterproductive. This is my major criticism, but I think we can make this work

**Comment by mb243** [comment]
> I feel that letting just new players built here would not be beneficial unless they are given permission to do so.

Are you referring to the spawn tutorial area or the city area with this?

IMO, the city area (for lack of a better term at the moment) is intended to be a central gathering place for folks to claim land and build at, set up shops, trading points, showcase their builds, etc. The land claim system is designed to grant users the control of taking ownership of land and deciding who else can use that area with them, and I think that the land claim system is the best tool for controlling access to all but essential parts of the map, which would be designated as server claims. From what I can tell, the current build was intended as a small, concentrated area without a plan for future outward expansion. There's certainly room to improve the current area, and as part of this, I had already pulled the claim back so that folks can tear down the outward wall to expand out how they wanted to. 

Also, just to add on to this, using Residence gives a lot more flexibility that Grief Prevention didn't. Specifically the ability to have claims that are limited in height. This can lend itself to having a "stacked" area where folks can rent out areas on different floors, or any number of different directions or methods for design and planning for future expansion. 

> Another important part is that everyone is equal to build here that deserves to.

Can you clarify this? How would you determine someone that 'deserves to'?

> I believe that to be a flaw with people building in The Old City.

It sounds like you're referring to the current `/city` area here. Is that right? Before addressing the points here, I just want to make sure that's correct.

> there are spots where people have started building but have claimed that no one can edit

With land claims, this is kind of an impossible-to-avoid situation, but designating the city areas as rentable could help mitigate this, as a player that's absent or doesn't pay their rent will lose their area, and the next person along could re-use that space. 

> Also props to the referral system

Thanks :)

**Comment by RetroRadical** [comment]
I kinda wanted to put both the tutorial and the city together, for some reason i thought that you got that without me saying anything lol

**Comment by RetroRadical** [comment]
Someone who deserves to add to the city is someone who we know would contribute something. And the current city is already the old city to me now because of how dead it is to me.

**Comment by mb243** [comment]
Just summing up what was discussed in PM:

> Blocktagon: So one of the things I'm open to is making a building-type structure. New players would spawn on the top, walk through the tutorial area, and end up at a region post/shop area when done
> Blocktagon: the area below this spawn platform could be the rentable city space

**Comment by mb243** [comment]
So, after getting some more feedback from @RetroRadical and reflecting on this more, I realize that my previous plan isn't going to work. It's too much time investment on my part and is overly complex for what it really needs to be. Additionally, every single player that joins a server is going to have a different idea of what they want or expect in a spawn, and one of the most frequent questions from new players is "Can I help you build a spawn?" For these reasons, I've decided to take it in a very minimal, player-centric, and flexible direction.

The new spawn/tutorial area will consist of two "zones":

- The small innermost zone will be where new players spawn and will consist of a region post and a set of signs that provide a minimal introduction to some of the server's most frequently-used commands.
- The outer zone will consist of areas of rentable and non-rentable space. Players can choose to rent any of the rentable space and do what they like with it, such as set up a shop or showcase a build, as long as rent is paid. If rent lapses, any other player have the option to rent the space and use it themselves.
- Beyond these two zones is the normal, open-world map for all players to claim and build on normally.

**Comment by mb243** [comment]
> ~~The outer zone will consist of areas of rentable and non-rentable space. Players can choose to rent any of the rentable space and do what they like with it, such as set up a shop or showcase a build, as long as rent is paid. If rent lapses, any other player have the option to rent the space and use it themselves.~~

Looking at this again, creating two zones will cause the protected land boundaries to extend out much further than is desirable, since new players will want to start building as quickly as possible, and putting additional constraints on them is undesirable. 

I've created a small protected area with tutorial signs and set it as the spawn point. PickleGinger's previous build at Tide region gets an honorable mention.

**Comment by mb243** [comment]
This is done
