### ISSUE TITLE
Move Getting Started guide to a set of pages?

### ISSUE THREAD

**Issue by mb243** [mb243/THBL#23]
The Getting Started guide is getting pretty long and goes over a lot of game mechanics in a single document, without much anchoring to directly link to certain things. 

I'd propose moving this to a set of pages which would break things like PvP mechanics, land claims, teleportation, economy, etc all out into separate pages, with a tl;dr at the beginning of each. This would mean more clicks to read all the topics but would lead to better organization of individual topics.

Thoughts?

**Comment by Acheron4171** [comment]
Sounds good to me.

**Comment by mb243** [comment]
This is done
