### ISSUE TITLE
Increasing the amount of subzones in a residence.

### ISSUE THREAD

**Issue by RetroRadical** [mb243/THBL#24]
I have reached a cap with the amount of subzones allowed in my res. Can we increase the number?

**Comment by mb243** [comment]
There are different options that could be adjusted. Can you give me some more detail on what you're trying to do and the limit that you're hitting?

**Comment by RetroRadical** [comment]
In the /res atlas, I tried to create another subzone using /res subzone atlas nameofsubzone, but instead of creating it, it said that you've reached the maximum amount of subclaims for this residence

**Comment by mb243** [comment]
Are you trying to subzone an already-existing subzone? Or create a new subzone within the top-level claim?

**Comment by RetroRadical** [comment]
The latter, make a new subclaim in my residence

**Comment by mb243** [comment]
Okay, I see the limit that you're hitting and I've increased it effective with the next server reboot. The new limit will be 16 subzones per claim. I'll close this issue for now, but if it doesn't work as expected tomorrow, re-open this issue and let me know.
