### ISSUE TITLE
Allow players to purchase NPC companions?

### ISSUE THREAD

**Issue by mb243** [mb243/THBL#25]
Looking to see if folks would be interested in the ability to purchase semi-customizable shop/combat NPC companions. They wouldn't be cheap and they would take damage and die like any other entity, but this might make a fun addition when other adventurers aren't able to join. Could also be a great touch for catacombs and what not. 

Let me know thoughts here. Could be a considerable amount of work, so I'm not going to do it unless there is significant interest.

**Comment by Acheron4171** [comment]
No big interest for combat companions from me. Unkillable noncombat companions might be cool. They follow you around, despawn when you die or logout and respawn when you respawn or log in.

**Comment by mb243** [comment]
Going to close this for now. The complexity of this isn't worth diving into unless there's a lot of interest.
