### ISSUE TITLE
Request: Postponing the removal of GP.

### ISSUE THREAD

**Issue by Acheron4171** [mb243/THBL#28]
I am so busy with school, dogs, not getting enough sleep, etc. that I'm not getting on the server anywhere near as much as I would like. I'm not even able to get on long enough to sort out my claims for the switch-over. I would like to request that the removal of GP not happen until I can manage to get on and sort out my claims.

**Comment by mb243** [comment]
Can you give me an idea of when you would be able to switch these over?

**Comment by Acheron4171** [comment]
Probably by the 7th. The quarter ends on the 23rd and then I have a several day trip to Idaho. I get back around the 1st. That should give me a week to get things straightened out.

**Comment by mb243** [comment]
I don't see why not. Sure.

**Comment by Acheron4171** [comment]
Thanks.

**Comment by mb243** [comment]
This has made it into the public announcements. Closing
