### ISSUE TITLE
/City region post no longer works

### ISSUE THREAD

**Issue by spikefire** [mb243/THBL#30]
/City region post no longer works. typing /city from another region post brings you to /spawn.

**Comment by RetroRadical** [comment]
I believe that region is called tide now

**Comment by therealph1x** [comment]
Tide is the nearest regular region post. The /city region post is the one in the middle of the main building.

**Comment by mb243** [comment]
This was an inherent limitation in PopulationDensity, which has been addressed with the switch to Residence TP
