### ISSUE TITLE
Slight Glitching When Running+Jumping

### ISSUE THREAD

**Issue by RetroRadical** [mb243/THBL#31]
I was sprinting forward in my claim and when I jumped while in sprint, I glitched causing the prompted asking me to tap sneak. It stops me for a brief moment then i continue sprinting. It happens fairly consistently and only just started happening tonight. 0/10 would not like to get kicked.

**Comment by mb243** [comment]
This might be fixed by changes that will take effect after the restart. Please check and let me know.

**Comment by mb243** [comment]
Is this still an issue?

**Comment by mb243** [comment]
Closing this for now. If it's still an issue, please re-open and share some more information.

**Comment by RetroRadical** [comment]
Yup, still an issue, just fell through the glass ceiling i had because of this

**Comment by RetroRadical** [comment]
When i sprint and i jump, glitch excessively upon the landing

**Comment by mb243** [comment]
> Yup, still an issue, just fell through the glass ceiling i had because of this

Based on my observations, I'm not fully convinced this specific issue is related.

Can you please try using the vanilla client only, without OptiFine or any other patches or launchers, and see if you're still having the same issue? 

Instructions on making sure you have a clean install are here:

http://minecraft.gamepedia.com/Tutorials/Minecraft_help_FAQ#Reinstalling_Minecraft

**Comment by mb243** [comment]
Closing this one for now. If you're still seeing this with a full vanilla client, please reopen and provide more details.
