### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by RetroRadical** [mb243/THBL#35]
Here is a few plugins I believe that we should put in to help new players.
1. A type of Random Teleportation System to get new players out into the wilderness.
https://www.spigotmc.org/resources/random-teleport-with-redprotect-kingdoms-worldguard-factions-towny-gp-worldborder-etc-support.29971/
2. Fun incentive to reward exploring. Traverse the lands of the Hard Block Life.
https://www.spigotmc.org/resources/chestdrop.10461/
3. I still feel like we should continue to build upon spawn. Using these can help fufill the tutorial aspect needed in spawn. We can put these above the posts in spawn, making their message more impactful.
https://mods.curse.com/bukkit-plugins/minecraft/holographic-displays

**Comment by mb243** [comment]
Can you close this issue and break each of these out into a separate issue to keep the discussions from getting cluttered and mixed up, please?
