### ISSUE TITLE
New Plugin Request. Random Loot Drop Chest

### ISSUE THREAD

**Issue by RetroRadical** [mb243/THBL#37]
Fun incentive to reward exploring. Traverse the lands of the Hard Block Life.
https://www.spigotmc.org/resources/chestdrop.10461/

**Comment by mb243** [comment]
This looks interesting.

Could you give some examples of items that might be tradable for gems, and how many gems each item would cost?

**Comment by mb243** [comment]
http://codisimus.com/phatloots was suggested too.

**Comment by RetroRadical** [comment]
I say do either, both, or something! Adding in rewards that favor those that play regularly. I don't want this to be an elytra, full enchanted armor and a stack of god apples, but some sort of reward worth the time. Also, we could go back to adding in the plugin with chests that spawned underneath monster spawners. I liked those too.

**Comment by mb243** [comment]
> ~~http://codisimus.com/phatloots~~

One of the key aspects when considering anything like this is fairness and less administrative effort. Phatloots uses chests in static locations that the admin creates, so a player could easily claim the chest and have exclusive access to it.

**Comment by mb243** [comment]
> ~~https://www.spigotmc.org/resources/chestdrop.10461/~~

This one is out as it uses new, specific lore items which have to be traded at a preconfigured rate for normal in-game items. It would be preferable if the chest generated normal in-game items from a loot table.

**Comment by mb243** [comment]
Here's a possibility:

- https://www.spigotmc.org/resources/%E2%98%85random-loot-chest%E2%98%85.26009/

**Comment by mb243** [comment]
Tested and implemented.
