### ISSUE TITLE
New Plugin Request. Further Customize Spawn with Holographic Displays

### ISSUE THREAD

**Issue by RetroRadical** [mb243/THBL#38]
I still feel like we should continue to build upon spawn. Using these can help fufill the tutorial aspect needed in spawn. We can put these above the posts in spawn, making their message more impactful.
https://mods.curse.com/bukkit-plugins/minecraft/holographic-displays

**Comment by mb243** [comment]
I don't know how I feel about this. There's something to be said for throwing *too much* information at a player when they first join. I feel that questions about gameplay have dropped significantly from new players with the spawn area signs, and I'm reinforcing this with AnswerBot as well. I don't really see the advantage of holographic displays for the spawn area, but I'm open to other thoughts here.

**Comment by mb243** [comment]
The original intent of #22 was to make sure that the information in the tutorial was succinct and could be absorbed quickly and by folks with a limited knowledge of English. Could you go into more detail on what advantage holographic signs could offer here?

**Comment by mb243** [comment]
Closing this for now. I don't see the value of this, but if anyone else wants to provide suggestions, please share.
