### ISSUE TITLE
Monsters

### ISSUE THREAD

**Issue by Acheron4171** [mb243/THBL#39]
I have been attacked by monsters that spawned in broad daylight. At least, I'm pretty sure they did. Can we check with others to see if they have had the same problem?

**Comment by mb243** [comment]
> I have been attacked by monsters that spawned in broad daylight. At least, I'm pretty sure they did. 

Could you please provide more information? Coordinates? Light level? Did the monsters spawn there, or did they move to that location? Were you moving or standing still?

I would need a lot more information before I could do any troubleshooting at all.

**Comment by Acheron4171** [comment]
It was on my island, in the middle of the day. I had just logged in so they weren't holdouts from the previous night. The skeles and zombies also were not burning. I do not know exact spawn locations but there is nowhere on my island that monsters can spawn during the day.

**Comment by mb243** [comment]
> The skeles and zombies also were not burning.

Do you have `burn` permission on your claim? Check `/res set`

> there is nowhere on my island that monsters can spawn during the day.

Can you clarify on this?

**Comment by Acheron4171** [comment]
> Do you have burn permission on your claim? Check /res set

I will check when I log on.

> there is nowhere on my island that monsters can spawn during the day.
> Can you clarify on this?

There is nowhere, on my island, that is dark enough for monsters to spawn during the day.

**Comment by mb243** [comment]
> It was on my island, in the middle of the day.

Which world was this in?

**Comment by Acheron4171** [comment]
> Which world was this in?

The Overworld.

> Okay, please let me know.

I ignite was off. I turned it on.

> Also, could you confirm if this only happened on a single real-world day, or did it happen over multiple days?

So far only in one real-world day. I have not been on during another day yet.

**Comment by Acheron4171** [comment]
Issue seems to be resolved. I'm closing the thread for now.
