### ISSUE TITLE
Flame bow

### ISSUE THREAD

**Issue by Acheron4171** [mb243/THBL#41]
My flame bow is not working on my claim. I have left my claim and it works. None of the fire related flags or the pvp flag have proved to be the culprit.

**Comment by mb243** [comment]
What claim is this for?

**Comment by Acheron4171** [comment]
Volcano

**Comment by mb243** [comment]
This claim appears to have `burn: false` and `firespread: false`. Can you try setting these to true and seeing if it resolves?

**Comment by Acheron4171** [comment]
> This claim appears to have burn: false and firespread: false. Can you try setting these to true and seeing if it resolves?

I already tried firespread and I do not have access to the burn flag.

**Comment by mb243** [comment]
Fixed the burn flag. Please check it now.

**Comment by Acheron4171** [comment]
> Fixed the burn flag. Please check it now.

Try again.

**Comment by mb243** [comment]
> Try again.

Is it still not working? Need more info here plz.

**Comment by Acheron4171** [comment]
Still no access to the burn flag.

**Comment by mb243** [comment]
Sorry. To clarify, I flipped the burn flag to true. I did not change access to that flag. 

Can you check if flame arrows are still an issue with firespread turned back on again?

**Comment by Acheron4171** [comment]
Flame arrows work now even without firespread.

**Comment by mb243** [comment]
Excellent! Looks like it was an issue with `burn` being set incorrectly. It was fixed on all claims in the overworld at the same time tonight.

Closing this now.
