### ISSUE TITLE
Chat text with '@' not being passed correctly from Minecraft to Discord

### ISSUE THREAD

**Issue by Acheron4171** [mb243/THBL#43]
Messages that start with "@" or "@discordname" aren't making it from MC to Discord.

**Comment by mb243** [comment]
Is this for messages that only start with these, or does it also affect messages that have these anywhere in them?

**Comment by Acheron4171** [comment]
It is for messages that have "@" anywhere but not for messages that have "@discordname" anywhere but the start. If that makes sense.

**Comment by mb243** [comment]
Is this still an issue since the overnight restart?

**Comment by mb243** [comment]
Is this still an issue since April 15th?

**Comment by Acheron4171** [comment]
Yes

**Comment by mb243** [comment]
Can you open an issue with the DiscordSRV issue tracker here please:

https://github.com/Scarsz/DiscordSRV/issues

**Comment by mb243** [comment]
Closing this for now. Please report it upstream and I'll wait for a patch to come down.

**Comment by Acheron4171** [comment]
It might be easier for you to report it. You know more about your server than I do.

**Comment by mb243** [comment]
This is a pretty low priority IMO, but I'll see if a patch comes down with the next release that's aimed for 1.12 fixed.

**Comment by mb243** [comment]
Is this still an issue with the latest update?

**Comment by Acheron4171** [comment]
You could check this yourself. lol

Kind of fixed.
It looks like only messages that start with "@" don't make it through.

**Comment by Acheron4171** [comment]
and messages with freestanding @s

**Comment by mb243** [comment]
> You could check this yourself.
I could, but permissions issues complicate things.

> It looks like only messages that start with "@" don't make it through.
Discord-to-MC, or MC-to-Discord?

> and messages with freestanding @s
@s is a new Minecraft reference. See [here](http://minecraft.gamepedia.com/1.12#Commands)

**Comment by Acheron4171** [comment]
> It looks like only messages that start with "@" don't make it through.

> Discord-to-MC, or MC-to-Discord?
MC-to-Discord

**Comment by mb243** [comment]
Looks like this is something that wouldn't normally come up in play, so I'm closing this for now.
