### ISSUE TITLE
Res Permissions Lists

### ISSUE THREAD

**Issue by Acheron4171** [mb243/THBL#44]
I created a Res permissions list named "Default" and ran the command "/res lists set Default admin false". It returned the output "Flag (%1) set for %2 to %3 state". My guess is the %numbers are variables that should have been replaced in the output.

**Comment by mb243** [comment]
Does is work correctly on claims with other names?

**Comment by Acheron4171** [comment]
That's not how lists work. For lists, you create the list, set the flags, then apply it to claims.

**Comment by mb243** [comment]
The name `default` is used internally for a few things, and might be why you're seeing this. Does this work correctly for permlists with other names?

**Comment by Acheron4171** [comment]
Let me try.

**Comment by Acheron4171** [comment]
/res lists set Hello_world admin removed
returns
Flag (%1) set for %2 to %3 state

**Comment by mb243** [comment]
Looks like an upstream bug. I've opened an issue with the plugin developer.

**Comment by Acheron4171** [comment]
Okay. Thanks for the prompt attention.

**Comment by mb243** [comment]
Closing this for now. It will need a fix upstream, which I'll then pull it once it's done.
