### ISSUE TITLE
Towering Glitch.

### ISSUE THREAD

**Issue by RetroRadical** [mb243/THBL#47]
Building straight up by jumping and placing a block beneath you while in air has a chance to throw you to the side.

**Comment by mb243** [comment]
Hmm. I thought I fixed this already. 
Can you give me date/time of this and what block you were building with?

**Comment by mb243** [comment]
Should be fixed. Can you confirm?

**Comment by RetroRadical** [comment]
Still getting the boot whilst towering

**Comment by mb243** [comment]
Check this once more and let me know.

**Comment by mb243** [comment]
Going to close this for now. If it comes back, please feel free to comment/reopen this.
