### ISSUE TITLE
Pigmen Heads have been Reset

### ISSUE THREAD

**Issue by RetroRadical** [mb243/THBL#48]
The texture for Pigmen heads have been converted to the Alex head.

**Comment by mb243** [comment]
Please try breaking/replacing the heads. This should fix them.

**Comment by Acheron4171** [comment]
We can't do that with the ones that the villagers are wearing.

**Comment by mb243** [comment]
It appears that the initial developer of the plugin that's used for this stopped making changes around 2 years ago, and the most recent fork stopped getting updated around 5 months ago. It's outside of my skill to fix, and the developers of the more recent forks don't have open issue trackers for this project that I can post this to.

This is probably one of those things that won't get a good fix and, although this doesn't appear to depend on NMS, is very likely to break even further with the upcoming update to 1.12.

Sorry, unless someone is willing to take on coding a fix for this themselves, there's honestly not much I can do here.
