### ISSUE TITLE
Multiple Wilderness Claims

### ISSUE THREAD

**Issue by Acheron4171** [mb243/THBL#5]
It would be nice if we either could request that certain posts be named or that we had access to /res tp and /res tpset. I was given LB's sky build and can never get out there because it takes too damn long. I'm sure that others have similar issues.

**Comment by mb243** [comment]
I don't agree with this. 

PopulationDensity allows people to fast-travel from one region to another, and the naming of regions is based on the presence of natural resources and player builds. The point of this is to allow fast travel within 'civilized' areas while maintaining the challenge and danger of visiting wilderness areas. 

It would be trivial for players to set up multiple small claims throughout the world and then use them to fast-travel pretty much whenever they wanted, which would significantly reduce the difficulty and risk of exploring.

**Comment by Acheron4171** [comment]
I see what you're saying. Maybe we just table this one for now. Zad has offered to help me figure out Nether portals and paths.
