### ISSUE TITLE
Anti Cheat Multi Interaction 

### ISSUE THREAD

**Issue by RetroRadical** [mb243/THBL#56]
Several times i have been kicked for fasting moving all of the same items from my inventory to a chest. Please fix :(

**Comment by mb243** [comment]
Can you provide some specifics on how you're moving these items?

**Comment by RetroRadical** [comment]
holding a stacking in my hand, then double clicking over another stack to fast move them into my inventory. they all go into my inventory then all go back into the chest.

**Comment by mb243** [comment]
There's an update queued up for tomorrow. Let me know if this is still an issue then.

**Comment by mb243** [comment]
Going to close this for now. Please re-open if it's still an issue.

**Comment by RetroRadical** [comment]
Still getting the boot.

**Comment by mb243** [comment]
Will be resolved with the next reboot
