### ISSUE TITLE
Ghosts; 2 spooky 4 me

### ISSUE THREAD

**Issue by RetroRadical** [mb243/THBL#6]
https://www.youtube.com/watch?v=ULq1W4HIhB8&feature=youtu.be im getting haunted by schism...

**Comment by mb243** [comment]
O_o

Is the date/time stamp on that video right?

**Comment by mb243** [comment]
> RetroRadical: 930 am March 1st

This is a more confusing one. I think I've found what caused it, though the logs don't confirm it as I would expect them to. I've made an adjustment, so if it happens again, let me know.
