### ISSUE TITLE
Mob Cap Despawning Crucial Endermites

### ISSUE THREAD

**Issue by RetroRadical** [mb243/THBL#68]
I believe my endermites in my enderfarm are being despawned because of the mob cap rule. please help :(

**Comment by mb243** [comment]
The mob capping is in place to prevent lag caused by the overpopulation of entities within chunks. I'd recommend that you make adjustments to your build to work around this.

**Comment by RetroRadical** [comment]
I know that but is there a way that there can be a change from deleting mobs if the limit is reached to stopping spawning, increasing the limit just a little more, or a minor tweak. It worked fine pre 1.12 but now this is happening :(

**Comment by mb243** [comment]
The potential to generate lag isn't properly mitigated if mobs simply stop spawning. If there's enough of them around, they can move from chunk to chunk and still cause issues. The only real ways to mitigate are to either stop movement, which is game unbalancing, or to kill/despawn them.

**Comment by Acheron4171** [comment]
Can you do a thing that says that endermites don't get killed

**Comment by mb243** [comment]
> Can you do a thing that says that endermites don't get killed?

The problem with this approach is the same problem that would occur if mobs wen't killed -- They would still be able to move from chunk to chunk creating a circumstance where a player could spawn a large number of them to cause a negative performance impact on the server.

I have already considered this for Villagers, but did not make the exception for the same reason.

**Comment by RetroRadical** [comment]
Mind me asking what the cap is?

**Comment by RetroRadical** [comment]
Could you reconsider if you took them from the shop? Enderman dont target spawn egg endermites anyway. lol

**Comment by mb243** [comment]
> Could you reconsider if you took them from the shop?

How would this impact the mechanics described below?

> If there's enough of them around, they can move from chunk to chunk and still cause issues. The only real ways to mitigate are to either stop movement, which is game unbalancing, or to kill/despawn them.

**Comment by mb243** [comment]
> Mind me asking what the cap is?

[maxEntityCramming](http://minecraft.gamepedia.com/Commands#gamerule) is set to 24, and can be considered a hard rule. 

Aside from that, there is another per-chunk entities limit which is currently set at 128, but shouldn't be considered a hard rule, as it may be adjusted if needed.

**Comment by RetroRadical** [comment]
I figured out what part was killing the endermite. its the exp orbs. Could you reinstall the xp stacking plugin?

**Comment by mb243** [comment]
^ Please open the above request as a new issue
