### ISSUE TITLE
Death from logging.

### ISSUE THREAD

**Issue by RetroRadical** [mb243/THBL#7]
I have died from logging out. I know the pvp rule for GP kills you upon logging out if you try to pvp, but i didnt fight anyone and i have pvp turned off in my claim. Honestly pissed af...

**Comment by mb243** [comment]
The log says...

> [01:48:40] [Server thread/INFO]: RetroRadical lost connection: Disconnected
> [01:48:40] [Server thread/INFO]: RetroRadical died
> [01:48:40] [Thread-2388/INFO]: > RetroRadical was killed for combat logging.

What this means is that you took damage within a certain period of time before you logged out. This could have been damage from any source -- PvP, hunger, environmental damage, a mob with thorns, falling, etc. The anti-cheat thought you were trying to avoid more damage and killed you when you logged out.

I looked over the time duration in the anti-cheat setting. It was a little high, so I've reduced it to a more reasonable value.
