### ISSUE TITLE
Reinstall Xp stacking

### ISSUE THREAD

**Issue by RetroRadical** [mb243/THBL#71]
Xp kills mobs when mob capped reached per chunk. Need Xp to be less of a hindrance. Consider stacking

**Comment by mb243** [comment]
Configured for next reboot. No take backs!

**Comment by Acheron4171** [comment]
But, but... Noooooo!!!!

**Comment by RetroRadical** [comment]
Id rather have working farms than unintentional killings

**Comment by Acheron4171** [comment]
:P
