### ISSUE TITLE
World map isn't working via Firefox.

### ISSUE THREAD

**Issue by Acheron4171** [mb243/THBL#75]
Every time I try to pull up the world map on Firefox, I get this message.

The requested URL /tiles/world/flat/-8_4/zzzzzzz_-256_128.jpg was not found on this server.

**Comment by mb243** [comment]
Do you see the same issues in other browsers?

**Comment by Acheron4171** [comment]
Map works with Safari and whatever Zad uses.

**Comment by mb243** [comment]
I haven't been able to reproduce this in Firefox. Please check to make sure you're using the latest version and try clearing your caches. Closing this for lack of information, but re-open if you're still able to reproduce.
